### ISSUE TITLE
Encoding overloaded no matter what settings I use for 1080p 60fps

### ISSUE THREAD

**Issue by T-Hitoshi** [fzwoch/obs-vaapi#16]
Hello, so I came over from [obs-gstreamer](https://github.com/fzwoch/obs-gstreamer) after a recommendation to switch to this instead. Previously I have been using `obs-gstreamer` because it is what works for me in 1080p 60fps. I have tried `obs-vaapi` before but kept encountering into "Encoding overloaded!" issues that I have not figured out a way to remedy since, but as mentioned works without issue when using the former.

I was looking into the list of open and closed issues and discovered other reports that mentions HEVC/H265, but on my end the overloading can also occur on H264.

Here are the details as I can provide:

inxi -SMC
```
System:
  Host: honoo-pc Kernel: 6.4.12-1-default arch: x86_64 bits: 64
    Desktop: KDE Plasma v: 5.27.7 Distro: openSUSE Tumbleweed 20230904
Machine:
  Type: Desktop System: ASUS product: N/A v: N/A serial: <superuser required>
  Mobo: ASUSTeK model: PRIME B560M-K v: Rev 1.xx
    serial: <superuser required> UEFI: American Megatrends v: 1605
    date: 05/13/2022
CPU:
  Info: 6-core model: 11th Gen Intel Core i5-11400F bits: 64 type: MT MCP
    cache: L2: 3 MiB
  Speed (MHz): avg: 2600 min/max: 800/2600 cores: 1: 2600 2: 2600 3: 2600
    4: 2600 5: 2600 6: 2600 7: 2600 8: 2600 9: 2600 10: 2600 11: 2600 12: 2600
```

inxi -Ga
```
Graphics:
  Device-1: AMD Polaris 20 XL [Radeon RX 580 2048SP] vendor: Sapphire
    driver: amdgpu v: kernel arch: GCN-4 code: Arctic Islands process: GF 14nm
    built: 2016-20 pcie: gen: 3 speed: 8 GT/s lanes: 16 ports:
    active: HDMI-A-1,HDMI-A-2 empty: DP-1,DP-2,DVI-D-1 bus-ID: 01:00.0
    chip-ID: 1002:6fdf class-ID: 0300 temp: 84.0 C
  Display: wayland server: X.org v: 1.21.1.8 with: Xwayland v: 23.2.0
    compositor: kwin_wayland driver: X: loaded: modesetting unloaded: fbdev,vesa
    dri: radeonsi gpu: amdgpu d-rect: 1920x2160 display-ID: 0
  Monitor-1: HDMI-A-1 pos: primary,top res: 1920x1080 size: N/A modes: N/A
  Monitor-2: HDMI-A-2 pos: bottom res: 1920x1080 size: N/A modes: N/A
  API: OpenGL v: 4.6 Mesa 23.1.6 renderer: AMD Radeon RX 580 2048SP
    (polaris10 LLVM 16.0.6 DRM 3.52 6.4.12-1-default) direct-render: Yes
```

vainfo
```Trying display: wayland
libva info: VA-API version 1.19.0
libva info: Trying to open /usr/lib64/dri/radeonsi_drv_video.so
libva info: Found init function __vaDriverInit_1_19
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.19 (libva 2.19.0)
vainfo: Driver version: Mesa Gallium driver 23.1.6 for AMD Radeon RX 580 2048SP (polaris10, LLVM 16.0.6, DRM 3.52, 6.4.12-1-default)
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            : VAEntrypointVLD
      VAProfileMPEG2Main              : VAEntrypointVLD
      VAProfileVC1Simple              : VAEntrypointVLD
      VAProfileVC1Main                : VAEntrypointVLD
      VAProfileVC1Advanced            : VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSlice
      VAProfileH264Main               : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointEncSlice
      VAProfileH264High               : VAEntrypointVLD
      VAProfileH264High               : VAEntrypointEncSlice
      VAProfileHEVCMain               : VAEntrypointVLD
      VAProfileHEVCMain               : VAEntrypointEncSlice
      VAProfileHEVCMain10             : VAEntrypointVLD
      VAProfileJPEGBaseline           : VAEntrypointVLD
      VAProfileNone                   : VAEntrypointVideoProc
```

Logfile: 
[2023-09-08 12-20-45.txt](https://github.com/fzwoch/obs-vaapi/files/12555475/2023-09-08.12-20-45.txt)
